### ISSUE TITLE
Focus not following when keyboard switching desktops

### ISSUE THREAD

**Issue by xmika** [newlooper/VirtualSpace#43] opened 2023-02-22 01:02 UTC
Pretty much a duplicate of #29 but I'm not using Cube3D? The next desktop won't remember where the focus was (and this is very annoying, either need to mouse click, alt+tab or set Windows setting to follow mouse for focus)

Is there something that can be done? VirtualSpace is something that I've been missing for a long time but this is pretty much the only problem I'm having. Ability to set "move active window to desktop X" shortcuts would be an amazing bonus.

Also when using Alt+numbers to switch desktops #29 steps to reproduce shows alt pressed state on the next desktop (especially easy to see with notepad when it's not in writing state but shows keyboard character hints...)

**Comment by newlooper** [comment] 2023-02-22 10:29
### 1. recover focus of ForegroundWindow after switch virtual desktop. 
try this PreRelease: [VirtualSpace_0.1.444.623_aio_net6.0_win-x64_noplugin_pre.zip](https://github.com/newlooper/VirtualSpace/files/10802616/VirtualSpace_0.1.444.623_aio_net6.0_win-x64_noplugin_pre.zip)

not fully tested, there should be no problem.

### 2. "move active window to desktop X" will be implemented in future version.

### 3. Using only `Alt` is not a good idea because it is the default key for triggering the main menu and can easily cause conflicts.

**Comment by xmika** [comment] 2023-02-22 10:59
1. Tried (and confirmed from settings that it's 444.623, W11 22H2) but no change, tried with terminal, notepad and edge both leaving input focused and only window focused but no change at all. After switching it won't focus last active window (or any other window for that matter).
2. Cool, thanks.
3. Very opinionated, after nearly 20 years with Linux I'm so used to using only alt and numbers and prefer to override the default behavior... (and even get rid of it completely if possible)

**Comment by newlooper** [comment] 2023-02-22 11:22
1. try close use VirtualSpace and use Windows way switch virtual desktop.

**Comment by xmika** [comment] 2023-02-22 11:39
After closing VirtualSpace and using Ctrl+Win+Left/Right focus works just like it should, ie. desktops 1, 2 & 3 all have focused application and switching between them recovers focus.

**Comment by newlooper** [comment] 2023-02-22 11:51
then try replicate this issue on another PC.
i have no this issue on my PC.

**Comment by xmika** [comment] 2023-02-22 12:40
I tried with another 22H2 PC but exactly the same thing, no matter what I do the focus won't recover. I tried adding new bindings to navigation left & right and different combinations to desktops, shortcut works without focus. 

With VirtualSpace running using Windows way Ctrl+Win+Left/Right it still switches but won't recover focus.

**Comment by newlooper** [comment] 2023-02-22 16:42
- step1. select Taskbar settings, select Taskbar behaviors, and select Automatically hide the taskbar.
- step2. close VirtualSpace, try use windows hotkey, see the effect.
- step3. open VirtualSpace, try use VirtualSpace hotkey, see the effect.

if the focus recovered in both step 2 and step 3, that is caused by the taskbar.
but if not, the cause of the problem will be difficult to capture.

btw, on my system, there is no problem with losing focus, whether the taskbar is hidden or not.

**Comment by xmika** [comment] 2023-02-23 19:04
Tested, I see that you published a new version with more shortcuts, nice.

Having taskbar hidden has no effect.

Step 2: Focus is recovered. 
Step 3: Focus remains on window where it was last obtained. If I open a window on desktop 3 it has the focus, switching to any other desktop won't get the focus and it remains on desktop 3. If I then open a new window on 1 it gets the focus and switch back to 3 no focus.

**Comment by newlooper** [comment] 2023-02-23 19:14
don't know if you are the only one experiencing this problem, or if others have encountered it as well.

suggestion:
install a VM (VMWare, VirtualBox, Hyper-V...), install a clean Windows, and test VirtualSpace.

**Comment by bigplayer-ai** [comment] 2023-02-27 21:47
I am using windows 11 22h2, The issue is not reproducible on my side. I use cube3d plugin.

**Comment by wayneguan26** [comment] 2023-03-03 19:40
I can reproduce the issue. it's really bad experience for fullscreen apps. hope it can be fixed.

my winver is 22H2, 22621.1344

**Comment by newlooper** [comment] 2023-03-04 08:43
each person's system environment is different, relying on guesswork is not reliable, but we should still try different solutions as much as possible.

here is one:

## becareful before you edit Windows Registry

1. If you don't know what the Windows Registry is and have never modified it, I suggest you don't do it
2. You are well aware of the role of the item you are modifying and its impact on the system
3. Leave a good way back, you have the ability to restore the modification if failure
4. see Steps

<details><summary>Steps</summary>
<p>

- open regedit.exe
- navigate to `HKEY_CURRENT_USER\Control Panel\Desktop\` and check the value of `ForegroundLockTimeout` (REG_DWORD)
- change that value to 0 if its not
- close regedit.exe and restart your system.

details of `ForegroundLockTimeout` can be found at [here](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc957208(v=technet.10)?redirectedfrom=MSDN)

</p>
</details>

**Comment by xmika** [comment] 2023-03-04 09:02
I'm going to test regedit when I get back home tonight. My girlfriend got a brand new Asus Zenbook with Windows 11 pro from her work and I literally opened it from the box and first thing tried VirtualSpace and the problem is present on that.

**Comment by wayneguan26** [comment] 2023-03-04 09:46
tried on my pc, it works every other time. which means the first switch works, the second doesn't, the third works, the forth doesn't...

**Comment by newlooper** [comment] 2023-03-04 11:46
try this [VirtualSpace.zip](https://github.com/newlooper/VirtualSpace/files/10888186/VirtualSpace.zip), and dont forget run it as administrator to avoid UIPI(UAC) issues.

if it resolving your problem, it will be published in next release.

**Comment by wayneguan26** [comment] 2023-03-04 11:50
> try this [VirtualSpace.zip](https://github.com/newlooper/VirtualSpace/files/10888186/VirtualSpace.zip), and dont forget run it as administrator to avoid UIPI(UAC) issues.
> 
> if it resolving your problem, it will be published in next release.

this is worse than before, other apps come on the top of fullscreen app.

**Comment by wayneguan26** [comment] 2023-03-04 11:51
> try this [VirtualSpace.zip](https://github.com/newlooper/VirtualSpace/files/10888186/VirtualSpace.zip), and dont forget run it as administrator to avoid UIPI(UAC) issues.
> 
> if it resolving your problem, it will be published in next release.

this is worse than before, other apps come on the top of fullscreen app.

**Comment by newlooper** [comment] 2023-03-04 11:54
make a screen record, then post here.

**Comment by wayneguan26** [comment] 2023-03-04 11:58
i deleted 22h2 and downloaded aio and replaced the exe, it works now. great!

**Comment by newlooper** [comment] 2023-03-04 12:03
download again, i make a new one.

**Comment by wayneguan26** [comment] 2023-03-04 12:10
> download again, i make a new one.

the same link? i tried, its the same, works only for the 1st switches, afterward taskbar is on the top of fullscreen app.

**Comment by newlooper** [comment] 2023-03-04 12:11
0.1.454.720. ?

**Comment by wayneguan26** [comment] 2023-03-04 12:14
wh

> 

what's this, the about screen shows 0.1.454.159.Win11_22H2

**Comment by newlooper** [comment] 2023-03-04 12:14
> > try this [VirtualSpace.zip](https://github.com/newlooper/VirtualSpace/files/10888238/VirtualSpace.zip), and dont forget run it as administrator to avoid UIPI(UAC) issues.
> > if it resolving your problem, it will be published in next release.
> 
> this is worse than before, other apps come on the top of fullscreen app.

**Comment by xmika** [comment] 2023-03-04 21:32
I tried regediting ForegroundLockTimeout, it was 20000, changing it to 0 had no effect.

Using the one from that VirtualSpace.zip is worse, it works on first switch but then it brings seemingly random window foreground that doesn't have focus.

**Comment by newlooper** [comment] 2023-03-05 01:35
try files in [release page](https://github.com/newlooper/VirtualSpace/releases), those are updated.

**Comment by wayneguan26** [comment] 2023-03-05 01:38
> try files in [release page](https://github.com/newlooper/VirtualSpace/releases), those are updated.

I tried. it works now. so far so good. thanks!

**Comment by wayneguan26** [comment] 2023-03-05 13:30
this f

> try files in [release page](https://github.com/newlooper/VirtualSpace/releases), those are updated.

this feature is broken in the latest version. please help~

**Comment by newlooper** [comment] 2023-03-05 13:42
make a screen record, post here.
it will save lot of words and time.

**Comment by wayneguan26** [comment] 2023-03-05 13:44
> make a screen record, post here. it will save lot of words and time.

i redownloaded the latest version. works good now. thanks!

**Comment by xmika** [comment] 2023-03-05 13:56
Latest version fixes the issue. Thanks!

**Comment by bigplayer-ai** [comment] 2023-03-08 07:15
New version does not have this issue. I tried to challenge it. No problem at all.

**Closed** 2023-04-24 08:31 UTC
